// A SCHEMA FOR EXAMS SCHEDULED FOR FUTURE: NAME AND TIME AND LT
// A SCHEMA FOR THE REQUESTS SENT: SUB, TIME, EXCEL SHEET LINK, TYPE? ANNOUNCE OR SCHEDULE

// UPON LOGIN OF A TEACHER, WHENEVER THE TEACHER TYPES IN THE TIME, THE FRONTEND CHECKS IN THE DB
// IF THE TEACHER HAS SCHEDULED ONE ALREADY OR IF THE TIME SLOT IS BOOKED AND RETURN FOFF IF SO.
// EACH SUB CAN HAVE ONLY ONE EXAM PER TIME AND NO REQUESTS UNTIL NEW OCCURRED.

// THE FRONTEND RECEIVES THE XLSX SHEET AND UPLOADS THEM TO GITHUB, THEN SEND THE DATA AS SCHEMA OBJECT TO BACKEND
// AND GETS STORED IN MONGODB

// ON OPENING THE ACCOUNT, THE ADMIN CAN VIEW ALL THE REQUESTS

